# Generated by Django 5.1.1 on 2024-09-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_id', models.CharField(max_length=100, unique=True)),
                ('type_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.IntegerField()),
                ('meal_plan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('star_rating', models.IntegerField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('business_registration_number', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('room_types', models.ManyToManyField(related_name='hotels', to='inventory.roomtype')),
            ],
        ),
    ]
