# Generated by Django 5.1.1 on 2024-09-18 15:45

import django.core.validators
import user_registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_alter_customuser_address_alter_customuser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business_registration_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_document',
            field=models.FileField(null=True, upload_to=user_registration.models.CustomUser.docs_upload_to),
        ),
    ]
